Modularise summary function
Deepomatic/cocoapi pull request #1
Opened 2021-02-24 15:46 UTC by putze

2021-02-24 15:59 UTC, vdel reviewed
It look good to me.

Do you know if there are some unit tests ? We could setup CI on travis to have automated tests.

I just "comment" for now until I have checked the related PRs.

2021-02-24 15:59 UTC, vdel commented on PythonAPI/pycocotools/cocoeval.py
> +        self.stats = stats
Yes ! Much better than before 👍 

I wonder what would be the impact of indexing `stats` by the key of `summary_config` instead of `i`? I think it could help removing some code in tensorflow/models: there is a part of the code where we remap the index to the name of the metric.

Also, I wonder what would be the impact of not storing the result in `self.stats` but to return it directly ?

2021-02-24 16:56 UTC, qtreh approved these changes
This looks ok

2021-02-24 19:15 UTC, vdel requested changes

2021-02-24 19:15 UTC, vdel commented on PythonAPI/pycocotools/cocoeval.py
> +        self.stats = stats
I reviewed the code in the other PR, it proposed changes that use the fact that `stats` is indexed by metric name. 

Could you please try if this would work with this ?

```python
for key, value in self.params.summary_config.items():
    stats[key] = self._summarize(**value)
self.stats = stats
```

2021-02-24 19:38 UTC, vdel approved these changes

2021-02-25 10:49 UTC, putze commented on PythonAPI/pycocotools/cocoeval.py
> +        self.stats = stats
It works perfectly well. I added this to the PR.

2021-02-25 10:49 UTC, merged